# Generated by Django 4.2.13 on 2024-05-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('ONE', '1 ROOMS whit AC'), ('YAC', 'Double bedroom with AC'), ('NAC', 'Double bedroom with out AC'), ('3AC', '3 ROOMS whit AC'), ('TWO', '2 ROOMS whit out AC')], max_length=5)),
                ('bed', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
