# Generated by Django 4.2.5 on 2024-06-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_room_category_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='price',
            name='room',
        ),
        migrations.RemoveField(
            model_name='price',
            name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('ONE', '1 ROOM flat whit AC'), ('YAC', 'Double bedroom with AC'), ('NAC', 'Double bedroom with out AC'), ('TWO', '2 ROOMS flat whit out AC'), ('3AC', '3 ROOMS flat whit AC')], max_length=3),
        ),
    ]
