# Generated by Django 4.2.5 on 2024-06-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_price_booking_remove_price_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, to='hotel.price'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('TWO', '2 ROOMS flat whit out AC'), ('YAC', 'Double bedroom with AC'), ('NAC', 'Double bedroom with out AC'), ('ONE', '1 ROOM flat whit AC'), ('3AC', '3 ROOMS flat whit AC')], max_length=3),
        ),
    ]
