# Generated by Django 4.2.5 on 2024-06-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_booking_price_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.price'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('NAC', 'Double bedroom with out AC'), ('TWO', '2 ROOMS flat whit out AC'), ('3AC', '3 ROOMS flat whit AC'), ('ONE', '1 ROOM flat whit AC'), ('YAC', 'Double bedroom with AC')], max_length=3),
        ),
    ]
