# Generated by Django 4.2.5 on 2024-06-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_booking_price_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'Double bedroom with AC'), ('NAC', 'Double bedroom with out AC'), ('ONE', '1 ROOM flat whit AC'), ('3AC', '3 ROOMS flat whit AC'), ('TWO', '2 ROOMS flat whit out AC')], max_length=3),
        ),
    ]
