# Generated by Django 4.2.5 on 2024-06-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('NAC', 'Double bedroom with out AC'), ('TWO', '2 ROOMS flat whit out AC'), ('YAC', 'Double bedroom with AC'), ('ONE', '1 ROOM flat whit AC'), ('3AC', '3 ROOMS flat whit AC')], max_length=3),
        ),
    ]
