# Generated by Django 5.0.6 on 2026-07-12 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=150, null=True)),
                ('pais', models.CharField(blank=True, max_length=150, null=True)),
                ('cumpleaños', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
