# Generated by Django 5.0.6 on 2026-06-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='birthday',
            new_name='cumpleaños',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='telefono',
        ),
    ]
