# Generated by Django 5.0.6 on 2026-06-09 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_contrato', models.TextField(blank=True, default='compuesta por 3 habitaciones numeradas del 1 al 3, un cuarto de baño, cocina y zonas comunes', max_length=1000, null=True)),
                ('aire_acondicionado', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=300)),
                ('toilet', models.IntegerField(default='1')),
                ('category', models.CharField(choices=[('TWO', 'Amplio y cómodo apartamento de dos dormitorios, ideal para estancias prolongadas. Su diseño moderno y funcional ofrece un ambiente acogedor con una luminosa zona de estar, cocina totalmente equipada y baño completo. Calefacción para el invierno. \n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA, con excelentes conexiones al centro de la ciudad. ¡Reserva ahora y disfruta de Madrid con comodidad y estilo!'), ('3AC', 'Amplio y moderno apartamento de tres dormitorios. Su diseño elegante y funcional ofrece una luminosa sala de estar, cocina totalmente equipada y baño completo. \n  Aire acondicionado para un confort ideal todo el año. \n  Ubicación estratégica, con excelentes conexiones y todos los servicios cercanos ¡Reserva tu estancia y disfruta de la comodidad con estilo!'), ('PLUS', 'Antigua casa española de carácter auténtico, rodeada por la calma de un jardín sencillo presidido por un olivo centenario. Sus dos cocinas y espacios luminosos la convierten en un lugar ideal tanto para el teletrabajo como para disfrutar de largas comidas al aire libre, en un ambiente sereno y acogedor de inspiración mediterránea.'), ('ONE', 'Disfruta de este moderno apartamento de un dormitorio, diseñado para ofrecer confort y estilo. Cuenta con aire acondicionado, una luminosa zona de estar y un baño totalmente equipado.\n Terraza privada ideal para relajarte o trabajar al aire libre.\n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA. ¡Reserva tu estancia y vive Madrid con el máximo confort!')], max_length=2000)),
                ('dimensiones', models.IntegerField(default=90)),
                ('wifi', models.BooleanField(default=True)),
                ('television', models.BooleanField(default=True)),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(default='img/room/default.jpg', upload_to='img/room')),
                ('title', models.TextField(blank=True, default='hola', max_length=1000, null=True)),
                ('description_image', models.TextField(blank=True, default='hola', max_length=1000, null=True)),
                ('image1', models.ImageField(blank=True, default='img/room/default.jpg', null=True, upload_to='img/room')),
                ('title1', models.TextField(blank=True, default='hola', max_length=1000, null=True)),
                ('description_image1', models.TextField(blank=True, default='hola', max_length=1000, null=True)),
                ('image2', models.ImageField(blank=True, default='img/room/default.jpg', null=True, upload_to='img/room')),
                ('title2', models.TextField(blank=True, default='hola', max_length=1000, null=True)),
                ('description_image2', models.TextField(blank=True, default='hola', max_length=1000, null=True)),
                ('image3', models.ImageField(blank=True, default='img/room/default.jpg', null=True, upload_to='img/room')),
                ('image4', models.ImageField(blank=True, default='img/room/default.jpg', null=True, upload_to='img/room')),
                ('image5', models.ImageField(blank=True, default='img/room/default.jpg', null=True, upload_to='img/room')),
                ('image6', models.ImageField(blank=True, default='img/room/default.jpg', null=True, upload_to='img/room')),
                ('subtitle', models.CharField(default='Estamos trabajando aquí', max_length=300)),
                ('description', models.TextField(default='Estamos trabajando aquí', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dni', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('nacionalidad', models.CharField(default='Española', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=200)),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(default='hola', max_length=100)),
                ('subtitle', models.CharField(default='hola', max_length=100)),
                ('capacity', models.IntegerField(default=1)),
                ('tv', models.BooleanField(default=True)),
                ('aire_acondicionado', models.BooleanField(default=False)),
                ('calefaccion', models.BooleanField(default=True)),
                ('bed', models.CharField(choices=[('ONE', 'Doble'), ('TWO', 'Simple')], default='ONE', max_length=100)),
                ('escritorio', models.BooleanField(default=True)),
                ('disponible', models.BooleanField(db_default=False)),
                ('bathroom', models.CharField(choices=[('TWO', 'Compartido'), ('ONE', 'En suite')], default='No', max_length=100)),
                ('share_kitchen', models.BooleanField(default=True)),
                ('terrace', models.BooleanField(default=False)),
                ('share_garden', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('image', models.ImageField(default='img/room/default.jpg', upload_to='img/room')),
                ('image1', models.ImageField(default='img/room/default.jpg', upload_to='img/room')),
                ('image2', models.ImageField(default='img/room/default.jpg', upload_to='img/room')),
                ('gastos', models.BooleanField(default=True)),
                ('precio', models.IntegerField(db_default=500)),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hotel.flat')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fianza', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='hotel.habitacion')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='hotel.inquilino')),
            ],
        ),
    ]
