# Generated by Django 5.0.6 on 2026-07-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_iteminventario_alter_flat_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='image2',
            field=models.ImageField(default='img/room/default.jpg', upload_to='img/room'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='image3',
            field=models.ImageField(default='img/room/default.jpg', upload_to='img/room'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='image4',
            field=models.ImageField(default='img/room/default.jpg', upload_to='img/room'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='category',
            field=models.CharField(choices=[('PLUS', 'Antigua casa española de carácter auténtico, rodeada por la calma de un jardín sencillo presidido por un olivo centenario. Sus dos cocinas y espacios luminosos la convierten en un lugar ideal tanto para el teletrabajo como para disfrutar de largas comidas al aire libre, en un ambiente sereno y acogedor de inspiración mediterránea.'), ('ONE', 'Disfruta de este moderno apartamento de un dormitorio, diseñado para ofrecer confort y estilo. Cuenta con aire acondicionado, una luminosa zona de estar y un baño totalmente equipado.\n Terraza privada ideal para relajarte o trabajar al aire libre.\n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA. ¡Reserva tu estancia y vive Madrid con el máximo confort!'), ('3AC', 'Amplio y moderno apartamento de tres dormitorios. Su diseño elegante y funcional ofrece una luminosa sala de estar, cocina totalmente equipada y baño completo. \n  Aire acondicionado para un confort ideal todo el año. \n  Ubicación estratégica, con excelentes conexiones y todos los servicios cercanos ¡Reserva tu estancia y disfruta de la comodidad con estilo!'), ('TWO', 'Amplio y cómodo apartamento de tres dormitorios, ideal para estancias prolongadas. Su diseño moderno y funcional ofrece un ambiente acogedor, cocina totalmente equipada y baño completo. Calefacción para el invierno. \n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA, con excelentes conexiones al centro de la ciudad. ¡Reserva ahora y disfruta de Madrid con comodidad y estilo!')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='flat',
            name='tipo_alquiler',
            field=models.CharField(choices=[('habitaciones', 'Alquiler por habitaciones'), ('completo', 'Alquiler piso completo')], default='habitaciones', max_length=20),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='bathroom',
            field=models.CharField(choices=[('ONE', 'En suite'), ('TWO', 'Compartido')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='bed',
            field=models.CharField(choices=[('ONE', 'Doble'), ('TWO', 'Simple')], default='ONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='subtitle',
            field=models.CharField(default='hola', max_length=500),
        ),
    ]
