# Generated by Django 5.0.6 on 2026-07-25 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_habitacion_image2_habitacion_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoalquiler',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='category',
            field=models.CharField(choices=[('ONE', 'Disfruta de este moderno apartamento de un dormitorio, diseñado para ofrecer confort y estilo. Cuenta con aire acondicionado, una luminosa zona de estar y un baño totalmente equipado.\n Terraza privada ideal para relajarte o trabajar al aire libre.\n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA. ¡Reserva tu estancia y vive Madrid con el máximo confort!'), ('PLUS', 'Antigua casa española de carácter auténtico, rodeada por la calma de un jardín sencillo presidido por un olivo centenario. Sus dos cocinas y espacios luminosos la convierten en un lugar ideal tanto para el teletrabajo como para disfrutar de largas comidas al aire libre, en un ambiente sereno y acogedor de inspiración mediterránea.'), ('3AC', 'Amplio y moderno apartamento de tres dormitorios. Su diseño elegante y funcional ofrece una luminosa sala de estar, cocina totalmente equipada y baño completo. \n  Aire acondicionado para un confort ideal todo el año. \n  Ubicación estratégica, con excelentes conexiones y todos los servicios cercanos ¡Reserva tu estancia y disfruta de la comodidad con estilo!'), ('TWO', 'Amplio y cómodo apartamento de tres dormitorios, ideal para estancias prolongadas. Su diseño moderno y funcional ofrece un ambiente acogedor, cocina totalmente equipada y baño completo. Calefacción para el invierno. \n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA, con excelentes conexiones al centro de la ciudad. ¡Reserva ahora y disfruta de Madrid con comodidad y estilo!')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='bathroom',
            field=models.CharField(choices=[('TWO', 'Compartido'), ('ONE', 'En suite')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='bed',
            field=models.CharField(choices=[('TWO', 'Simple'), ('ONE', 'Doble')], default='ONE', max_length=100),
        ),
        migrations.CreateModel(
            name='AvalContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('dni_nie', models.CharField(max_length=20)),
                ('domicilio', models.CharField(blank=True, max_length=200)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aval', to='hotel.contratoalquiler')),
            ],
        ),
    ]
