# Generated by Django 5.0.6 on 2026-07-26 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_habitacion_reparto_gastos_flat_reparto_gastos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='category',
            field=models.CharField(choices=[('ONE', 'Disfruta de este moderno apartamento de un dormitorio, diseñado para ofrecer confort y estilo. Cuenta con aire acondicionado, una luminosa zona de estar y un baño totalmente equipado.\n Terraza privada ideal para relajarte o trabajar al aire libre.\n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA. ¡Reserva tu estancia y vive Madrid con el máximo confort!'), ('TWO', 'Amplio y cómodo apartamento de tres dormitorios, ideal para estancias prolongadas. Su diseño moderno y funcional ofrece un ambiente acogedor, cocina totalmente equipada y baño completo. Calefacción para el invierno. \n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA, con excelentes conexiones al centro de la ciudad. ¡Reserva ahora y disfruta de Madrid con comodidad y estilo!'), ('PLUS', 'Antigua casa española de carácter auténtico, rodeada por la calma de un jardín sencillo presidido por un olivo centenario. Sus dos cocinas y espacios luminosos la convierten en un lugar ideal tanto para el teletrabajo como para disfrutar de largas comidas al aire libre, en un ambiente sereno y acogedor de inspiración mediterránea.'), ('3AC', 'Amplio y moderno apartamento de tres dormitorios. Su diseño elegante y funcional ofrece una luminosa sala de estar, cocina totalmente equipada y baño completo. \n  Aire acondicionado para un confort ideal todo el año. \n  Ubicación estratégica, con excelentes conexiones y todos los servicios cercanos ¡Reserva tu estancia y disfruta de la comodidad con estilo!')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='flat',
            name='reparto_gastos',
            field=models.CharField(choices=[('IGUAL', 'A partes iguales'), ('POR_TIPO_HABITACION', 'Según tipo de habitación')], default='IGUAL', max_length=30, verbose_name='Sistema de reparto de gastos'),
        ),
        migrations.CreateModel(
            name='ProcesoFormalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de iniciar'), ('INICIADO', 'En plazo de formalización'), ('FORMALIZADO', 'Formalizado'), ('CADUCADO', 'Caducado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('datos_confirmados', models.BooleanField(default=False)),
                ('contrato_descargado', models.BooleanField(default=False)),
                ('fecha_descarga', models.DateTimeField(blank=True, null=True)),
                ('contrato_firmado_recibido', models.BooleanField(default=False)),
                ('fianza_recibida', models.BooleanField(default=False)),
                ('renta_recibida', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proceso_formalizacion', to='hotel.contratoalquiler')),
            ],
        ),
    ]
