# Generated by Django 5.0.6 on 2026-06-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_habitacion_armario_alter_flat_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='image',
            new_name='cocina',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='description_image',
            new_name='cocina_description',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='description_image1',
            new_name='cocina_title',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='image1',
            new_name='terraza',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='description_image2',
            new_name='terraza_descripcion',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='title',
            new_name='terraza_title',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='image2',
            new_name='wc',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='title1',
            new_name='wc_description',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='title2',
            new_name='wc_title',
        ),
        migrations.AlterField(
            model_name='flat',
            name='category',
            field=models.CharField(choices=[('3AC', 'Amplio y moderno apartamento de tres dormitorios. Su diseño elegante y funcional ofrece una luminosa sala de estar, cocina totalmente equipada y baño completo. \n  Aire acondicionado para un confort ideal todo el año. \n  Ubicación estratégica, con excelentes conexiones y todos los servicios cercanos ¡Reserva tu estancia y disfruta de la comodidad con estilo!'), ('PLUS', 'Antigua casa española de carácter auténtico, rodeada por la calma de un jardín sencillo presidido por un olivo centenario. Sus dos cocinas y espacios luminosos la convierten en un lugar ideal tanto para el teletrabajo como para disfrutar de largas comidas al aire libre, en un ambiente sereno y acogedor de inspiración mediterránea.'), ('TWO', 'Amplio y cómodo apartamento de dos dormitorios, ideal para estancias prolongadas. Su diseño moderno y funcional ofrece un ambiente acogedor con una luminosa zona de estar, cocina totalmente equipada y baño completo. Calefacción para el invierno. \n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA, con excelentes conexiones al centro de la ciudad. ¡Reserva ahora y disfruta de Madrid con comodidad y estilo!'), ('ONE', 'Disfruta de este moderno apartamento de un dormitorio, diseñado para ofrecer confort y estilo. Cuenta con aire acondicionado, una luminosa zona de estar y un baño totalmente equipado.\n Terraza privada ideal para relajarte o trabajar al aire libre.\n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA. ¡Reserva tu estancia y vive Madrid con el máximo confort!')], max_length=2000),
        ),
    ]
