# Generated by Django 5.0.6 on 2026-07-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_procesoformalizacion_duracion_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoformalizacion',
            name='importe_primera_renta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='procesoformalizacion',
            name='inquilino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesos_formalizacion', to='hotel.inquilino'),
        ),
        migrations.AddField(
            model_name='procesoformalizacion',
            name='tipo_primera_renta',
            field=models.CharField(choices=[('MES_COMPLETO', 'Mes completo'), ('PROPORCIONAL', 'Parte proporcional')], default='PROPORCIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='flat',
            name='category',
            field=models.CharField(choices=[('ONE', 'Disfruta de este moderno apartamento de un dormitorio, diseñado para ofrecer confort y estilo. Cuenta con aire acondicionado, una luminosa zona de estar y un baño totalmente equipado.\n Terraza privada ideal para relajarte o trabajar al aire libre.\n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA. ¡Reserva tu estancia y vive Madrid con el máximo confort!'), ('3AC', 'Amplio y moderno apartamento de tres dormitorios. Su diseño elegante y funcional ofrece una luminosa sala de estar, cocina totalmente equipada y baño completo. \n  Aire acondicionado para un confort ideal todo el año. \n  Ubicación estratégica, con excelentes conexiones y todos los servicios cercanos ¡Reserva tu estancia y disfruta de la comodidad con estilo!'), ('TWO', 'Amplio y cómodo apartamento de tres dormitorios, ideal para estancias prolongadas. Su diseño moderno y funcional ofrece un ambiente acogedor, cocina totalmente equipada y baño completo. Calefacción para el invierno. \n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA, con excelentes conexiones al centro de la ciudad. ¡Reserva ahora y disfruta de Madrid con comodidad y estilo!'), ('PLUS', 'Antigua casa española de carácter auténtico, rodeada por la calma de un jardín sencillo presidido por un olivo centenario. Sus dos cocinas y espacios luminosos la convierten en un lugar ideal tanto para el teletrabajo como para disfrutar de largas comidas al aire libre, en un ambiente sereno y acogedor de inspiración mediterránea.')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='flat',
            name='tipo_alquiler',
            field=models.CharField(choices=[('habitaciones', 'Alquiler por habitaciones'), ('completo', 'Alquiler piso completo')], default='habitaciones', max_length=20),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='bathroom',
            field=models.CharField(choices=[('ONE', 'En suite'), ('TWO', 'Compartido')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='bed',
            field=models.CharField(choices=[('TWO', 'Simple'), ('ONE', 'Doble')], default='ONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='procesoformalizacion',
            name='duracion_meses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
