# Generated by Django 5.0.6 on 2026-08-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_flat_category_alter_flat_tipo_alquiler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoformalizacion',
            name='aval_dni_nie',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='procesoformalizacion',
            name='aval_domicilio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='procesoformalizacion',
            name='aval_nombre_completo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='procesoformalizacion',
            name='tiene_aval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flat',
            name='category',
            field=models.CharField(choices=[('TWO', 'Amplio y cómodo apartamento de tres dormitorios, ideal para estancias prolongadas. Su diseño moderno y funcional ofrece un ambiente acogedor, cocina totalmente equipada y baño completo. Calefacción para el invierno. \n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA, con excelentes conexiones al centro de la ciudad. ¡Reserva ahora y disfruta de Madrid con comodidad y estilo!'), ('ONE', 'Disfruta de este moderno apartamento de un dormitorio, diseñado para ofrecer confort y estilo. Cuenta con aire acondicionado, una luminosa zona de estar y un baño totalmente equipado.\n Terraza privada ideal para relajarte o trabajar al aire libre.\n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA. ¡Reserva tu estancia y vive Madrid con el máximo confort!'), ('PLUS', 'Antigua casa española de carácter auténtico, rodeada por la calma de un jardín sencillo presidido por un olivo centenario. Sus dos cocinas y espacios luminosos la convierten en un lugar ideal tanto para el teletrabajo como para disfrutar de largas comidas al aire libre, en un ambiente sereno y acogedor de inspiración mediterránea.'), ('3AC', 'Amplio y moderno apartamento de tres dormitorios. Su diseño elegante y funcional ofrece una luminosa sala de estar, cocina totalmente equipada y baño completo. \n  Aire acondicionado para un confort ideal todo el año. \n  Ubicación estratégica, con excelentes conexiones y todos los servicios cercanos ¡Reserva tu estancia y disfruta de la comodidad con estilo!')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='bed',
            field=models.CharField(choices=[('TWO', 'Simple'), ('ONE', 'Doble')], default='ONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='telefono',
            field=models.CharField(blank=True, help_text='Incluye el prefijo internacional, por ejemplo +34 o +57.', max_length=25, null=True, verbose_name='Teléfono / WhatsApp'),
        ),
    ]
