# Generated by Django 5.0.6 on 2026-08-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_alter_multimediahabitacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='grupo_bano',
            field=models.CharField(blank=True, help_text='Habitaciones con el mismo texto comparten baño. Ejemplo: HARO_BANO_PLANTA_BAJA.', max_length=80, verbose_name='Grupo de baño'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='grupo_cocina',
            field=models.CharField(blank=True, help_text='Habitaciones con el mismo texto comparten cocina. Ejemplo: HARO_COCINA_1.', max_length=80, verbose_name='Grupo de cocina'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='category',
            field=models.CharField(choices=[('TWO', 'Amplio y cómodo apartamento de tres dormitorios, ideal para estancias prolongadas. Su diseño moderno y funcional ofrece un ambiente acogedor, cocina totalmente equipada y baño completo. Calefacción para el invierno. \n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA, con excelentes conexiones al centro de la ciudad. ¡Reserva ahora y disfruta de Madrid con comodidad y estilo!'), ('PLUS', 'Antigua casa española de carácter auténtico, rodeada por la calma de un jardín sencillo presidido por un olivo centenario. Sus dos cocinas y espacios luminosos la convierten en un lugar ideal tanto para el teletrabajo como para disfrutar de largas comidas al aire libre, en un ambiente sereno y acogedor de inspiración mediterránea.'), ('3AC', 'Amplio y moderno apartamento de tres dormitorios. Su diseño elegante y funcional ofrece una luminosa sala de estar, cocina totalmente equipada y baño completo. \n  Aire acondicionado para un confort ideal todo el año. \n  Ubicación estratégica, con excelentes conexiones y todos los servicios cercanos ¡Reserva tu estancia y disfruta de la comodidad con estilo!'), ('ONE', 'Disfruta de este moderno apartamento de un dormitorio, diseñado para ofrecer confort y estilo. Cuenta con aire acondicionado, una luminosa zona de estar y un baño totalmente equipado.\n Terraza privada ideal para relajarte o trabajar al aire libre.\n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA. ¡Reserva tu estancia y vive Madrid con el máximo confort!')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='bathroom',
            field=models.CharField(choices=[('TWO', 'Compartido'), ('ONE', 'En suite')], default='No', max_length=100),
        ),
    ]
