# Generated by Django 5.0.6 on 2026-08-19 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_habitacion_grupo_bano_habitacion_grupo_cocina_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha', '-fecha_creacion'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasto',
            name='justificante',
            field=models.FileField(blank=True, null=True, upload_to='gastos/justificantes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='flat',
            name='category',
            field=models.CharField(choices=[('3AC', 'Amplio y moderno apartamento de tres dormitorios. Su diseño elegante y funcional ofrece una luminosa sala de estar, cocina totalmente equipada y baño completo. \n  Aire acondicionado para un confort ideal todo el año. \n  Ubicación estratégica, con excelentes conexiones y todos los servicios cercanos ¡Reserva tu estancia y disfruta de la comodidad con estilo!'), ('ONE', 'Disfruta de este moderno apartamento de un dormitorio, diseñado para ofrecer confort y estilo. Cuenta con aire acondicionado, una luminosa zona de estar y un baño totalmente equipado.\n Terraza privada ideal para relajarte o trabajar al aire libre.\n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA. ¡Reserva tu estancia y vive Madrid con el máximo confort!'), ('PLUS', 'Antigua casa española de carácter auténtico, rodeada por la calma de un jardín sencillo presidido por un olivo centenario. Sus dos cocinas y espacios luminosos la convierten en un lugar ideal tanto para el teletrabajo como para disfrutar de largas comidas al aire libre, en un ambiente sereno y acogedor de inspiración mediterránea.'), ('TWO', 'Amplio y cómodo apartamento de tres dormitorios, ideal para estancias prolongadas. Su diseño moderno y funcional ofrece un ambiente acogedor, cocina totalmente equipada y baño completo. Calefacción para el invierno. \n Ubicación estratégica, cerca del Aeropuerto de Madrid-Barajas y IFEMA, con excelentes conexiones al centro de la ciudad. ¡Reserva ahora y disfruta de Madrid con comodidad y estilo!')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='flat',
            name='tipo_alquiler',
            field=models.CharField(choices=[('completo', 'Alquiler piso completo'), ('habitaciones', 'Alquiler por habitaciones')], default='habitaciones', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('limpieza', 'Limpieza'), ('suministros', 'Suministros'), ('reparacion', 'Reparación'), ('mejora', 'Mejoras'), ('mobiliario', 'Mobiliario'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos'), ('otros', 'Otros')], default='otros', max_length=30),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='notas',
            field=models.TextField(blank=True, default='nada'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['fecha'], name='hotel_gasto_fecha_c0ff33_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['propiedad', 'fecha'], name='hotel_gasto_propied_6badc1_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['categoria', 'fecha'], name='hotel_gasto_categor_6123be_idx'),
        ),
    ]
