# Generated by Django 5.0.6 on 2026-08-31 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_alter_flat_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(blank=True, help_text='Ej: Monstera deliciosa', max_length=150)),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Terraza, salón, entrada, junto a la ventana...', max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Presentación o personalidad de la planta')),
                ('cuidados', models.TextField(blank=True, help_text='Indicaciones básicas de cuidado')),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Actualmente en la vivienda'), ('fallecida', 'Fallecida'), ('retirada', 'Retirada')], default='activa', max_length=20)),
                ('generacion', models.PositiveIntegerField(default=1, help_text='Petra I, Petra II, Petra III...')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='plantas/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('publica', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantas', to='hotel.habitacion')),
                ('piso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantas', to='hotel.flat')),
            ],
        ),
        migrations.CreateModel(
            name='EventoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llegada', 'Llegada'), ('estancia', 'Estancia'), ('incidente', 'Incidente'), ('fallecimiento', 'Fallecimiento'), ('reemplazo', 'Reemplazo'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('publico', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='hotel.planta')),
            ],
            options={
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('fecha_inicio_estancia', models.DateField(blank=True, null=True)),
                ('fecha_fin_estancia', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='plantas/comentarios/')),
                ('aprobado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='hotel.planta')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
