# Generated by Django 5.0.6 on 2026-09-05 01:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_planta_eventoplanta_comentarioplanta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('categoria_predeterminada', models.CharField(blank=True, choices=[('suministros', 'Suministros'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos y tasas'), ('mantenimiento', 'Mantenimiento'), ('reparacion', 'Reparaciones'), ('mobiliario', 'Mobiliario'), ('equipamiento', 'Equipamiento'), ('limpieza', 'Limpieza'), ('gestion', 'Gestión'), ('desplazamiento', 'Desplazamientos'), ('software', 'Software y servicios digitales'), ('marketing', 'Marketing'), ('seguros', 'Seguros'), ('otros', 'Otros')], max_length=40)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='gasto',
            name='ambito',
            field=models.CharField(choices=[('propiedad', 'Una propiedad'), ('habitacion', 'Una habitación'), ('empresa', 'Gestión general')], default='propiedad', max_length=20),
        ),
        migrations.AddField(
            model_name='gasto',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasto',
            name='generado_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasto',
            name='periodo_recurrente',
            field=models.DateField(blank=True, help_text='Primer día del periodo al que corresponde el gastos recurrente.', null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('recurrente', 'Recurrente'), ('extraordinario', 'Extraordinario'), ('inversion', 'Inversión'), ('gestion', 'Gestión')], default='extraordinario', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('suministros', 'Suministros'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos y tasas'), ('mantenimiento', 'Mantenimiento'), ('reparacion', 'Reparaciones'), ('mobiliario', 'Mobiliario'), ('equipamiento', 'Equipamiento'), ('limpieza', 'Limpieza'), ('gestion', 'Gestión'), ('desplazamiento', 'Desplazamientos'), ('software', 'Software y servicios digitales'), ('marketing', 'Marketing'), ('seguros', 'Seguros'), ('otros', 'Otros')], default='otros', max_length=30),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='concepto',
            field=models.CharField(blank=True, help_text='Añade una explicación solamente cuando la categoría y el proveedor no sean suficientes.', max_length=150, verbose_name='Descripción opcional'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='pagado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gasto', to='hotel.flat'),
        ),
        migrations.CreateModel(
            name='GastoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ambito', models.CharField(choices=[('propiedad', 'Una propiedad'), ('habitacion', 'Una habitación'), ('empresa', 'Gestión general')], default='propiedad', max_length=20)),
                ('categoria', models.CharField(choices=[('suministros', 'Suministros'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos y tasas'), ('mantenimiento', 'Mantenimiento'), ('reparacion', 'Reparaciones'), ('mobiliario', 'Mobiliario'), ('equipamiento', 'Equipamiento'), ('limpieza', 'Limpieza'), ('gestion', 'Gestión'), ('desplazamiento', 'Desplazamientos'), ('software', 'Software y servicios digitales'), ('marketing', 'Marketing'), ('seguros', 'Seguros'), ('otros', 'Otros')], default='otros', max_length=30)),
                ('tipo', models.CharField(choices=[('recurrente', 'Recurrente'), ('extraordinario', 'Extraordinario'), ('inversion', 'Inversión'), ('gestion', 'Gestión')], default='recurrente', max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('concepto', models.CharField(blank=True, max_length=150, verbose_name='Descripción opcional')),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('dia_generacion', models.PositiveSmallIntegerField(default=1)),
                ('mes_generacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('pagado_por_defecto', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_recurrentes', to='hotel.habitacion')),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_recurrentes', to='hotel.flat')),
            ],
            options={
                'verbose_name': 'Gasto recurrente',
                'verbose_name_plural': 'Gastos recurrentes',
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='gasto_recurrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_generados', to='hotel.gastorecurrente'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['habitacion', 'fecha'], name='hotel_gasto_habitac_ea63eb_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['tipo', 'fecha'], name='hotel_gasto_tipo_afcb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['ambito', 'fecha'], name='hotel_gasto_ambito_3fd59e_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['pagado', 'fecha'], name='hotel_gasto_pagado_3a9b45_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['anulado', 'fecha'], name='hotel_gasto_anulado_45cae8_idx'),
        ),
        migrations.AddConstraint(
            model_name='gasto',
            constraint=models.UniqueConstraint(condition=models.Q(('gasto_recurrente__isnull', False), ('periodo_recurrente__isnull', False)), fields=('gasto_recurrente', 'periodo_recurrente'), name='gasto_recurrente_periodo_unico'),
        ),
    ]
