# Generated by Django 5.0.6 on 2026-09-05 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_proveedor_gasto_ambito_gasto_anulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='destino_gestoria',
            field=models.CharField(choices=[('gestoria', 'Enviar a gestoría'), ('interno', 'Solo control interno')], default='gestoria', max_length=20, verbose_name='Destino del justificante'),
        ),
        migrations.AddField(
            model_name='gastorecurrente',
            name='destino_gestoria',
            field=models.CharField(choices=[('gestoria', 'Enviar a gestoría'), ('interno', 'Solo control interno')], default='revisar', max_length=20),
        ),
        migrations.AddField(
            model_name='gastorecurrente',
            name='modo_importe',
            field=models.CharField(choices=[('fijo', 'Importe fijo'), ('variable', 'Importe variable')], default='fijo', max_length=20),
        ),
        migrations.AddField(
            model_name='gastorecurrente',
            name='requiere_justificante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='hotel.habitacion'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='hotel.flat'),
        ),
        migrations.AlterField(
            model_name='gastorecurrente',
            name='frecuencia',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Cada 2 meses'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20),
        ),
        migrations.CreateModel(
            name='GastoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de completar'), ('completado', 'Completado'), ('omitido', 'Omitido')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('gasto_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_pendiente', to='hotel.gasto')),
                ('gasto_recurrente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendientes', to='hotel.gastorecurrente')),
            ],
            options={
                'verbose_name': 'Gasto pendiente',
                'verbose_name_plural': 'Gastos pendientes',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.AddConstraint(
            model_name='gastopendiente',
            constraint=models.UniqueConstraint(fields=('gasto_recurrente', 'periodo'), name='pendiente_recurrente_periodo_unico'),
        ),
    ]
