# Generated by Django 5.0.6 on 2026-09-06 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_gasto_destino_gestoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('pais', models.CharField(choices=[('ES', 'España'), ('AR', 'Argentina')], max_length=2)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('provincia', models.CharField(blank=True, max_length=120)),
                ('tipo', models.CharField(choices=[('aparthotel', 'Aparthotel'), ('vivienda', 'Vivienda'), ('reforma', 'Reforma'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('estado', models.CharField(choices=[('planificacion', 'Planificación'), ('desarrollo', 'En desarrollo'), ('operativo', 'Operativo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado')], default='planificacion', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['pais', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='pais',
            field=models.CharField(choices=[('ES', 'España'), ('AR', 'Argentina')], default='ES', max_length=2),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='ambito',
            field=models.CharField(choices=[('propiedad', 'Una propiedad'), ('empresa', 'Gestión general'), ('proyecto', 'Proyecto')], default='propiedad', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('suministros', 'Suministros'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos y tasas'), ('reparacion', 'Reparaciones'), ('Mejoras', 'Mejoras'), ('gestion', 'Gestión'), ('gestion remota', 'gestion remota'), ('hipotecas y seguros', 'hipotecas y seguros'), ('otros', 'Otros')], default='otros', max_length=30),
        ),
        migrations.AlterField(
            model_name='gastorecurrente',
            name='ambito',
            field=models.CharField(choices=[('propiedad', 'Una propiedad'), ('empresa', 'Gestión general'), ('proyecto', 'Proyecto')], default='propiedad', max_length=20),
        ),
        migrations.AlterField(
            model_name='gastorecurrente',
            name='categoria',
            field=models.CharField(choices=[('suministros', 'Suministros'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos y tasas'), ('reparacion', 'Reparaciones'), ('Mejoras', 'Mejoras'), ('gestion', 'Gestión'), ('gestion remota', 'gestion remota'), ('hipotecas y seguros', 'hipotecas y seguros'), ('otros', 'Otros')], default='otros', max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='categoria_predeterminada',
            field=models.CharField(blank=True, choices=[('suministros', 'Suministros'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos y tasas'), ('reparacion', 'Reparaciones'), ('Mejoras', 'Mejoras'), ('gestion', 'Gestión'), ('gestion remota', 'gestion remota'), ('hipotecas y seguros', 'hipotecas y seguros'), ('otros', 'Otros')], max_length=40),
        ),
        migrations.AddField(
            model_name='gasto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='hotel.proyecto'),
        ),
    ]
