# Generated by Django 5.0.6 on 2026-06-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_alter_flat_category_alter_habitacion_bathroom'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""ALTER TABLE hotel_habitacion
            RENAME COLUMN price TO precio;
            """,
            reverse_sql="""
                ALTER TABLE hotel_habitacion
                RENAME COLUMN precio TO price
            """
        ),
    ]
