# Generated by Django 5.0.6 on 2026-09-06 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_proyecto_gasto_pais_alter_gasto_ambito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastorecurrente',
            name='modo_importe',
        ),
        migrations.AddField(
            model_name='gasto',
            name='consumo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Permite analizar el consumo real de electricidad, agua o gas.', max_digits=12, null=True, verbose_name='Consumo'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo_suministro',
            field=models.CharField(blank=True, choices=[('electricidad', 'Electricidad'), ('agua', 'Agua'), ('gas', 'Gas'), ('internet', 'Internet'), ('telefonia', 'Telefonía'), ('otros', 'Otros suministros')], max_length=20, verbose_name='Tipo de suministro'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='unidad_consumo',
            field=models.CharField(blank=True, choices=[('kwh', 'kWh'), ('m3', 'm³'), ('litros', 'Litros'), ('unidades', 'Unidades')], max_length=20, verbose_name='Unidad de consumo'),
        ),
        migrations.AddField(
            model_name='gastorecurrente',
            name='pais',
            field=models.CharField(choices=[('ES', 'España'), ('AR', 'Argentina')], db_index=True, default='ES', max_length=2),
        ),
        migrations.AddField(
            model_name='gastorecurrente',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_recurrentes', to='hotel.proyecto'),
        ),
        migrations.AddField(
            model_name='gastorecurrente',
            name='tipo_suministro',
            field=models.CharField(blank=True, choices=[('electricidad', 'Electricidad'), ('agua', 'Agua'), ('gas', 'Gas'), ('internet', 'Internet'), ('telefonia', 'Telefonía'), ('otros', 'Otros suministros')], max_length=20, verbose_name='Tipo de suministro'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='ambito',
            field=models.CharField(choices=[('empresa', 'Sociedad y gestión general'), ('propiedad', 'Una propiedad'), ('proyecto', 'Un proyecto')], default='propiedad', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('suministros', 'Suministros'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos y tasas'), ('reparaciones', 'Reparaciones y mantenimiento'), ('mejoras', 'Mejoras e inversión'), ('gestion', 'Gestión y servicios profesionales'), ('gestion_remota', 'Gestión remota'), ('hipotecas_seguros', 'Hipotecas y seguros'), ('otros', 'Otros')], default='otros', max_length=30),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='pais',
            field=models.CharField(choices=[('ES', 'España'), ('AR', 'Argentina')], db_index=True, default='ES', max_length=2),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='periodo_recurrente',
            field=models.DateField(blank=True, help_text='Primer día del periodo al que corresponde el gasto recurrente.', null=True),
        ),
        migrations.AlterField(
            model_name='gastorecurrente',
            name='ambito',
            field=models.CharField(choices=[('empresa', 'Sociedad y gestión general'), ('propiedad', 'Una propiedad'), ('proyecto', 'Un proyecto')], default='propiedad', max_length=20),
        ),
        migrations.AlterField(
            model_name='gastorecurrente',
            name='categoria',
            field=models.CharField(choices=[('suministros', 'Suministros'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos y tasas'), ('reparaciones', 'Reparaciones y mantenimiento'), ('mejoras', 'Mejoras e inversión'), ('gestion', 'Gestión y servicios profesionales'), ('gestion_remota', 'Gestión remota'), ('hipotecas_seguros', 'Hipotecas y seguros'), ('otros', 'Otros')], default='otros', max_length=30),
        ),
        migrations.AlterField(
            model_name='gastorecurrente',
            name='destino_gestoria',
            field=models.CharField(choices=[('gestoria', 'Enviar a gestoría'), ('interno', 'Solo control interno')], default='gestoria', max_length=20),
        ),
        migrations.AlterField(
            model_name='gastorecurrente',
            name='frecuencia',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Cada dos meses'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20),
        ),
        migrations.AlterField(
            model_name='gastorecurrente',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='categoria_predeterminada',
            field=models.CharField(blank=True, choices=[('suministros', 'Suministros'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos y tasas'), ('reparaciones', 'Reparaciones y mantenimiento'), ('mejoras', 'Mejoras e inversión'), ('gestion', 'Gestión y servicios profesionales'), ('gestion_remota', 'Gestión remota'), ('hipotecas_seguros', 'Hipotecas y seguros'), ('otros', 'Otros')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['pais', 'fecha'], name='hotel_gasto_pais_952164_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['proyecto', 'fecha'], name='hotel_gasto_proyect_0f5961_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['tipo_suministro', 'fecha'], name='hotel_gasto_tipo_su_f4b255_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['destino_gestoria', 'fecha'], name='hotel_gasto_destino_e3e2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='gastorecurrente',
            index=models.Index(fields=['pais', 'activo'], name='hotel_gasto_pais_c492c8_idx'),
        ),
        migrations.AddIndex(
            model_name='gastorecurrente',
            index=models.Index(fields=['propiedad', 'activo'], name='hotel_gasto_propied_5d21f3_idx'),
        ),
        migrations.AddIndex(
            model_name='gastorecurrente',
            index=models.Index(fields=['proyecto', 'activo'], name='hotel_gasto_proyect_07faeb_idx'),
        ),
        migrations.AddIndex(
            model_name='gastorecurrente',
            index=models.Index(fields=['categoria', 'activo'], name='hotel_gasto_categor_f7eb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='gastorecurrente',
            index=models.Index(fields=['tipo_suministro', 'activo'], name='hotel_gasto_tipo_su_03edb8_idx'),
        ),
    ]
