# Generated by Django 5.0.6 on 2026-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_remove_gastorecurrente_modo_importe_gasto_consumo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['pais', 'nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='categoria_predeterminada',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(choices=[('ES', 'España'), ('AR', 'Argentina')], db_index=True, default='ES', max_length=2),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('pais', 'nombre'), name='proveedor_unico_por_pais'),
        ),
    ]
