# Generated by Django 5.0.6 on 2026-09-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='cotizacion_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Pesos argentinos equivalentes a un dólar.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha_cotizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='fuente_cotizacion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gasto',
            name='importe_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='moneda',
            field=models.CharField(choices=[('EUR', 'Euro'), ('ARS', 'Peso argentino')], default='EUR', max_length=3),
        ),
    ]
