# Generated by Django 5.0.6 on 2026-09-07 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_gasto_cotizacion_usd_gasto_fecha_cotizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('presupuesto_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='hotel.proyecto')),
            ],
            options={
                'verbose_name': 'Partida presupuestaria',
                'verbose_name_plural': 'Partidas presupuestarias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='partidaproyecto',
            constraint=models.UniqueConstraint(fields=('proyecto', 'nombre'), name='partida_unica_por_proyecto'),
        ),
    ]
