# Generated by Django 5.0.6 on 2026-09-12 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_partidaproyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(blank=True, max_length=150)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('pagador', models.CharField(blank=True, max_length=120, verbose_name='Nombre o referencia del pagador')),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='hotel.flat')),
            ],
            options={
                'verbose_name': 'Ingreso de propiedad',
                'verbose_name_plural': 'Ingresos de propiedades',
                'ordering': ['-fecha', '-fecha_creacion'],
                'indexes': [models.Index(fields=['propiedad', 'fecha'], name='hotel_ingre_propied_c27a14_idx')],
            },
        ),
    ]
