# Generated by Django 5.0.6 on 2026-10-01 14:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_ingresopropiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('suministros', 'Suministros'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos y tasas'), ('reparaciones', 'Reparaciones y mantenimiento'), ('mejoras', 'Mejoras e inversión'), ('gestion', 'Gestión y direccion ejecutiva'), ('gestion_remota', 'Gestión remota'), ('hipotecas_seguros', 'Hipotecas y seguros'), ('otros', 'Otros')], default='otros', max_length=30),
        ),
        migrations.AlterField(
            model_name='gastorecurrente',
            name='categoria',
            field=models.CharField(choices=[('suministros', 'Suministros'), ('comunidad', 'Comunidad'), ('impuestos', 'Impuestos y tasas'), ('reparaciones', 'Reparaciones y mantenimiento'), ('mejoras', 'Mejoras e inversión'), ('gestion', 'Gestión y direccion ejecutiva'), ('gestion_remota', 'Gestión remota'), ('hipotecas_seguros', 'Hipotecas y seguros'), ('otros', 'Otros')], default='otros', max_length=30),
        ),
        migrations.CreateModel(
            name='Hipoteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=150, verbose_name='Entidad bancaria')),
                ('referencia', models.CharField(blank=True, max_length=150, verbose_name='Referencia')),
                ('capital_inicial', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Capital inicial')),
                ('deuda_pendiente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Deuda pendiente')),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cuota mensual')),
                ('tipo_interes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tipo de interés (%)')),
                ('plazo_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazo en meses')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hipotecas', to='hotel.flat', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Hipoteca',
                'verbose_name_plural': 'Hipotecas',
                'ordering': ['propiedad__nombre', 'entidad'],
            },
        ),
        migrations.CreateModel(
            name='PagoHipoteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('importe_cuota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe total de la cuota')),
                ('intereses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Intereses')),
                ('capital_amortizado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Capital amortizado')),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Otros gastos')),
                ('justificante', models.FileField(blank=True, null=True, upload_to='hipotecas/justificantes/%Y/%m/')),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hipoteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='hotel.hipoteca', verbose_name='Hipoteca')),
            ],
            options={
                'verbose_name': 'Pago de hipoteca',
                'verbose_name_plural': 'Pagos de hipoteca',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='pagohipoteca',
            constraint=models.UniqueConstraint(fields=('hipoteca', 'fecha'), name='pago_hipoteca_unico_por_fecha'),
        ),
    ]
