# Generated by Django 5.0.6 on 2026-10-01 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_alter_gasto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hipoteca',
            options={'ordering': ['entidad', 'propiedad'], 'verbose_name': 'Prestamo', 'verbose_name_plural': 'Hipotecas'},
        ),
        migrations.AddField(
            model_name='hipoteca',
            name='dia_cobro',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Día de cobro'),
        ),
        migrations.AddField(
            model_name='pagohipoteca',
            name='gasto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_hipoteca', to='hotel.gasto'),
        ),
        migrations.AlterField(
            model_name='hipoteca',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hipoteca',
            name='entidad',
            field=models.CharField(max_length=100, verbose_name='Entidad bancaria'),
        ),
        migrations.AlterField(
            model_name='hipoteca',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia / número de préstamo'),
        ),
        migrations.AlterField(
            model_name='hipoteca',
            name='tipo_interes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tipo de interés (%)'),
        ),
    ]
