# Generated by Django 5.0.6 on 2026-10-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0033_renombrar_hipotecas_a_prestamos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagoprestamo',
            options={'ordering': ['-fecha', '-fecha_creacion'], 'verbose_name': 'Pago de préstamo', 'verbose_name_plural': 'Pagos de préstamo'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['entidad', 'tipo']},
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo',
            field=models.CharField(choices=[('hipoteca', 'Hipoteca'), ('personal', 'Préstamo personal'), ('ico', 'Préstamo ICO'), ('otro', 'Otro')], default='hipoteca', max_length=20, verbose_name='Tipo de préstamo'),
        ),
        migrations.AlterField(
            model_name='pagoprestamo',
            name='gasto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_prestamo', to='hotel.gasto'),
        ),
        migrations.AlterField(
            model_name='pagoprestamo',
            name='justificante',
            field=models.FileField(blank=True, null=True, upload_to='prestamos/justificantes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='pagoprestamo',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='hotel.prestamo', verbose_name='Préstamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='entidad',
            field=models.CharField(max_length=100, verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='hotel.flat', verbose_name='Propiedad vinculada'),
        ),
        migrations.AddConstraint(
            model_name='pagoprestamo',
            constraint=models.UniqueConstraint(fields=('prestamo', 'fecha'), name='pago_prestamo_unico_por_fecha'),
        ),
    ]
