# Generated by Django 5.0.6 on 2026-10-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0034_alter_pagoprestamo_options_alter_prestamo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='diferencial',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Diferencial sobre Euríbor'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_proxima_revision',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima revisión'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='frecuencia_revision_meses',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(6, 'Cada 6 meses'), (12, 'Cada 12 meses')], null=True, verbose_name='Revisión'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo_tasa',
            field=models.CharField(choices=[('fijo', 'Fijo'), ('variable', 'Variable')], default='variable', max_length=10, verbose_name='Tipo de interés'),
        ),
    ]
