# Generated by Django 5.0.6 on 2026-10-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0035_prestamo_diferencial_prestamo_fecha_proxima_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoprestamo',
            name='estimado',
            field=models.BooleanField(default=False, verbose_name='Pago estimado'),
        ),
    ]
