# Generated by Django 5.0.6 on 2026-10-02 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0036_pagoprestamo_estimado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('pais', models.CharField(max_length=100)),
                ('moneda', models.CharField(default='EUR', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sociedad',
                'verbose_name_plural': 'Sociedades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='hotel.sociedad', verbose_name='Sociedad'),
        ),
    ]
